package edu.hawaii.stack;

/**
 * EmptyStackException is thrown when an attempt is made to pop an empty stack.
 *
 * @author Philip M. Johnson
 */
public class EmptyStackException extends Exception {

  /**
   * The serial version UID, autogenerated by Eclipse. 
   */
  private static final long serialVersionUID = 7236818507144587981L;

  /**
   * Indicates an illegal operation on an empty stack was performed.
   * @param e The exception thrown.
   */
  public EmptyStackException(Exception e) {
    super(e.getMessage());
  }
}
